FROM golang:1.20-bullseye as base

WORKDIR /app
COPY . ./
WORKDIR /app/example/tictactoe

RUN CGO_ENABLED=0 GOOS=linux go build -o /cmd

FROM gcr.io/distroless/static-debian11

COPY --from=base /cmd .
COPY --from=base /app/ /app/


CMD [ "/cmd" ]
