FROM golang:1.20-bullseye as base

WORKDIR /app

COPY ./example/tictactoe/go.mod /app/example/tictactoe/go.mod
COPY ./example/tictactoe/go.sum /app/example/tictactoe/go.sum
WORKDIR /app/example/tictactoe
RUN go mod download

COPY . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o /cmd

FROM gcr.io/distroless/static-debian11

COPY --from=base /cmd .
COPY --from=base /app/ /app/


CMD [ "/cmd" ]
