apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: k3d-myregistry.localhost:12345/auth:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: k3d-myregistry.localhost:12345/account:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sociallist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sociallist
  template:
    metadata:
      labels:
        app: sociallist
    spec:
      containers:
      - name: sociallist
        image: k3d-myregistry.localhost:12345/sociallist:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: k3d-myregistry.localhost:12345/tictactoe:latest
        ports:
        - containerPort: 8080
