apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: k3d-myregistry.localhost:12345/tictactoe:latest
        ports:
        - containerPort: 8911
          name: gossip
        env:
        - name: ACCOUNT_URL
          value: "account.default.svc.cluster.local:8080"
        - name: AUTH_URL
          value: "auth.default.svc.cluster.local:8080"
        - name: GOSSIP_ADDR
          value: "tictactoe.default.svc.cluster.local"
        command: ["/cmd"]
        args: ["-account_url","$(ACCOUNT_URL)","-auth_url","$(AUTH_URL)","-gossip_addr","$(GOSSIP_ADDR)"]
---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe
spec:
  selector:
    app: tictactoe
  ports:
    - protocol: UDP
      port: 8911
      targetPort: 8911
