// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/grapevine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a Contact lookup by accountId
type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string         `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Address   *ClientAddress `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Contact) GetAddress() *ClientAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type Search struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requestor *Contact `protobuf:"bytes,1,opt,name=requestor,proto3" json:"requestor,omitempty"`
	Query     string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Search) Reset() {
	*x = Search{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{1}
}

func (x *Search) GetRequestor() *Contact {
	if x != nil {
		return x.Requestor
	}
	return nil
}

func (x *Search) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// A gossip message can/may be repeated till endOfLife reached or dropped before
type Gossip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndOfLife *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=endOfLife,proto3" json:"endOfLife,omitempty"`
	// Types that are assignable to GossipUnion:
	//
	//	*Gossip_Search
	GossipUnion isGossip_GossipUnion `protobuf_oneof:"GossipUnion"`
}

func (x *Gossip) Reset() {
	*x = Gossip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gossip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gossip) ProtoMessage() {}

func (x *Gossip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gossip.ProtoReflect.Descriptor instead.
func (*Gossip) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{2}
}

func (x *Gossip) GetEndOfLife() *timestamppb.Timestamp {
	if x != nil {
		return x.EndOfLife
	}
	return nil
}

func (m *Gossip) GetGossipUnion() isGossip_GossipUnion {
	if m != nil {
		return m.GossipUnion
	}
	return nil
}

func (x *Gossip) GetSearch() *Search {
	if x, ok := x.GetGossipUnion().(*Gossip_Search); ok {
		return x.Search
	}
	return nil
}

type isGossip_GossipUnion interface {
	isGossip_GossipUnion()
}

type Gossip_Search struct {
	Search *Search `protobuf:"bytes,2,opt,name=search,proto3,oneof"`
}

func (*Gossip_Search) isGossip_GossipUnion() {}

type GossipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gossip []*Gossip `protobuf:"bytes,1,rep,name=gossip,proto3" json:"gossip,omitempty"`
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{3}
}

func (x *GossipRequest) GetGossip() []*Gossip {
	if x != nil {
		return x.Gossip
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gossip []*Gossip `protobuf:"bytes,1,rep,name=gossip,proto3" json:"gossip,omitempty"`
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{4}
}

func (x *GossipResponse) GetGossip() []*Gossip {
	if x != nil {
		return x.Gossip
	}
	return nil
}

type SharedInvitationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SharedInvitationRequest) Reset() {
	*x = SharedInvitationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedInvitationRequest) ProtoMessage() {}

func (x *SharedInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedInvitationRequest.ProtoReflect.Descriptor instead.
func (*SharedInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{5}
}

type SharedInvitationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SharedInvitationResponse) Reset() {
	*x = SharedInvitationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedInvitationResponse) ProtoMessage() {}

func (x *SharedInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedInvitationResponse.ProtoReflect.Descriptor instead.
func (*SharedInvitationResponse) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{6}
}

type ChangeDataOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeDataOwnerRequest) Reset() {
	*x = ChangeDataOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDataOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataOwnerRequest) ProtoMessage() {}

func (x *ChangeDataOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataOwnerRequest.ProtoReflect.Descriptor instead.
func (*ChangeDataOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{7}
}

type ChangeDataOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeDataOwnerResponse) Reset() {
	*x = ChangeDataOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDataOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataOwnerResponse) ProtoMessage() {}

func (x *ChangeDataOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataOwnerResponse.ProtoReflect.Descriptor instead.
func (*ChangeDataOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{8}
}

type ChangeDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeDataRequest) Reset() {
	*x = ChangeDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataRequest) ProtoMessage() {}

func (x *ChangeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataRequest.ProtoReflect.Descriptor instead.
func (*ChangeDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{9}
}

type ChangeDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeDataResponse) Reset() {
	*x = ChangeDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataResponse) ProtoMessage() {}

func (x *ChangeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataResponse.ProtoReflect.Descriptor instead.
func (*ChangeDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{10}
}

type LeaveSharedDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveSharedDataRequest) Reset() {
	*x = LeaveSharedDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveSharedDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSharedDataRequest) ProtoMessage() {}

func (x *LeaveSharedDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSharedDataRequest.ProtoReflect.Descriptor instead.
func (*LeaveSharedDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{11}
}

type LeaveSharedDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveSharedDataResponse) Reset() {
	*x = LeaveSharedDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grapevine_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveSharedDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSharedDataResponse) ProtoMessage() {}

func (x *LeaveSharedDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grapevine_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSharedDataResponse.ProtoReflect.Descriptor instead.
func (*LeaveSharedDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_grapevine_proto_rawDescGZIP(), []int{12}
}

var File_proto_grapevine_proto protoreflect.FileDescriptor

var file_proto_grapevine_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x76, 0x69, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4c, 0x0a, 0x06,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x7a, 0x0a, 0x06, 0x47, 0x6f,
	0x73, 0x73, 0x69, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x4c, 0x69, 0x66,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x4c, 0x69, 0x66, 0x65, 0x12, 0x27,
	0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x0d, 0x0a, 0x0b, 0x47, 0x6f, 0x73, 0x73, 0x69,
	0x70, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0d, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x67, 0x6f, 0x73, 0x73, 0x69,
	0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x06, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x22, 0x37,
	0x0a, 0x0e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x06, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52,
	0x06, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x0a, 0x16, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x85, 0x03, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x70, 0x65, 0x76, 0x69, 0x6e,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x47, 0x6f, 0x73, 0x73,
	0x69, 0x70, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x79, 0x6c, 0x65, 0x31,
	0x39, 0x37, 0x34, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x76, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grapevine_proto_rawDescOnce sync.Once
	file_proto_grapevine_proto_rawDescData = file_proto_grapevine_proto_rawDesc
)

func file_proto_grapevine_proto_rawDescGZIP() []byte {
	file_proto_grapevine_proto_rawDescOnce.Do(func() {
		file_proto_grapevine_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grapevine_proto_rawDescData)
	})
	return file_proto_grapevine_proto_rawDescData
}

var file_proto_grapevine_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_grapevine_proto_goTypes = []interface{}{
	(*Contact)(nil),                  // 0: proto.Contact
	(*Search)(nil),                   // 1: proto.Search
	(*Gossip)(nil),                   // 2: proto.Gossip
	(*GossipRequest)(nil),            // 3: proto.GossipRequest
	(*GossipResponse)(nil),           // 4: proto.GossipResponse
	(*SharedInvitationRequest)(nil),  // 5: proto.SharedInvitationRequest
	(*SharedInvitationResponse)(nil), // 6: proto.SharedInvitationResponse
	(*ChangeDataOwnerRequest)(nil),   // 7: proto.ChangeDataOwnerRequest
	(*ChangeDataOwnerResponse)(nil),  // 8: proto.ChangeDataOwnerResponse
	(*ChangeDataRequest)(nil),        // 9: proto.ChangeDataRequest
	(*ChangeDataResponse)(nil),       // 10: proto.ChangeDataResponse
	(*LeaveSharedDataRequest)(nil),   // 11: proto.LeaveSharedDataRequest
	(*LeaveSharedDataResponse)(nil),  // 12: proto.LeaveSharedDataResponse
	(*ClientAddress)(nil),            // 13: proto.ClientAddress
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_proto_grapevine_proto_depIdxs = []int32{
	13, // 0: proto.Contact.address:type_name -> proto.ClientAddress
	0,  // 1: proto.Search.requestor:type_name -> proto.Contact
	14, // 2: proto.Gossip.endOfLife:type_name -> google.protobuf.Timestamp
	1,  // 3: proto.Gossip.search:type_name -> proto.Search
	2,  // 4: proto.GossipRequest.gossip:type_name -> proto.Gossip
	2,  // 5: proto.GossipResponse.gossip:type_name -> proto.Gossip
	3,  // 6: proto.GrapevineService.Gossip:input_type -> proto.GossipRequest
	5,  // 7: proto.GrapevineService.SharedInvitation:input_type -> proto.SharedInvitationRequest
	7,  // 8: proto.GrapevineService.ChangeDataOwner:input_type -> proto.ChangeDataOwnerRequest
	9,  // 9: proto.GrapevineService.ChangeData:input_type -> proto.ChangeDataRequest
	11, // 10: proto.GrapevineService.LeaveSharedData:input_type -> proto.LeaveSharedDataRequest
	4,  // 11: proto.GrapevineService.Gossip:output_type -> proto.GossipResponse
	6,  // 12: proto.GrapevineService.SharedInvitation:output_type -> proto.SharedInvitationResponse
	8,  // 13: proto.GrapevineService.ChangeDataOwner:output_type -> proto.ChangeDataOwnerResponse
	10, // 14: proto.GrapevineService.ChangeData:output_type -> proto.ChangeDataResponse
	12, // 15: proto.GrapevineService.LeaveSharedData:output_type -> proto.LeaveSharedDataResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_grapevine_proto_init() }
func file_proto_grapevine_proto_init() {
	if File_proto_grapevine_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_grapevine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gossip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedInvitationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedInvitationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDataOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDataOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveSharedDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grapevine_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveSharedDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_grapevine_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Gossip_Search)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grapevine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grapevine_proto_goTypes,
		DependencyIndexes: file_proto_grapevine_proto_depIdxs,
		MessageInfos:      file_proto_grapevine_proto_msgTypes,
	}.Build()
	File_proto_grapevine_proto = out.File
	file_proto_grapevine_proto_rawDesc = nil
	file_proto_grapevine_proto_goTypes = nil
	file_proto_grapevine_proto_depIdxs = nil
}
